In [1]:
import numpy as np
import pandas as pd

# Data Cleaning

When we receive raw data, we have to do a number of things before we’re ready to analyze it, possibly including:

* **Diagnose the Data**
* **Reshaping the Data**
* **Dealing with Duplicates**
* **Splitting by Index**
* **Splitting by Character**
* **Looking at Types**
* **String Parsing**
* **Dealing with Missing Values**

## Diagnose the Data

We often describe data that is easy to analyze and visualize as **tidy data**. 

What does it mean to have tidy data?

For data to be tidy, it must have:

* **Each variable as a separate column**
* **Each row as a separate observation**

The first step of diagnosing whether or not a dataset is tidy is **using pandas functions to explore and probe the dataset**.

Some useful dataset diagnostic:

|Code|Descriptions|
|---|---|
|.head()| display the first 5 rows of the table|
|.info() |display a summary of the table|
|.describe()| display the summary statistics of the table|
|.columns| display the column names of the table|
|.value_counts() |display the distinct values for a column|

Example:

Given a data:

In [2]:
students = pd.DataFrame({
    "full_name":["Moses Kirckman","Timofei Strowan","Silvain Poll","Lezley Pinxton","Bernadene Saunper"],
    "gender_age":["M14","M14","M14","M15","F17"],
    "fractions":["76%","83%","83%","80%","67%"],
    "probability":["72%",np.nan,np.nan,"86%","78%"],
    "grade":["9th grade","12th grade","12th grade","11th grade","10th grade"]
})

In [3]:
#first 5 rows of the table
students.head()

           full_name gender_age fractions probability       grade
0     Moses Kirckman        M14       76%         72%   9th grade
1    Timofei Strowan        M14       83%         NaN  12th grade
2       Silvain Poll        M14       83%         NaN  12th grade
3     Lezley Pinxton        M15       80%         86%  11th grade
4  Bernadene Saunper        F17       67%         78%  10th grade

In [4]:
#summary of the table
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   full_name    5 non-null      object
 1   gender_age   5 non-null      object
 2   fractions    5 non-null      object
 3   probability  3 non-null      object
 4   grade        5 non-null      object
dtypes: object(5)
memory usage: 332.0+ bytes

In [5]:
#summary statistics of the table
students.describe()

             full_name gender_age fractions probability       grade
count                5          5         5           3           5
unique               5          3         4           3           4
top     Moses Kirckman        M14       83%         72%  12th grade
freq                 1          3         2           1           2

In [6]:
#column names of the table
students.columns

Index(['full_name', 'gender_age', 'fractions', 'probability', 'grade'], dtype='object')

In [7]:
#distinct values for each column
for column in students.columns:
    print(students[column].value_counts())
    print("\n")

full_name
Moses Kirckman       1
Timofei Strowan      1
Silvain Poll         1
Lezley Pinxton       1
Bernadene Saunper    1
Name: count, dtype: int64


gender_age
M14    3
M15    1
F17    1
Name: count, dtype: int64


fractions
83%    2
76%    1
80%    1
67%    1
Name: count, dtype: int64


probability
72%    1
86%    1
78%    1
Name: count, dtype: int64


grade
12th grade    2
9th grade     1
11th grade    1
10th grade    1
Name: count, dtype: int64

## Reshape Data

Since we want

* **Each variable as a separate column**
* **Each row as a separate observation**

We want from this

||full_name|	gender_age|	fractions|	probability	|grade|
|---|---|---|---|---|---|
|0|	Moses Kirckman|	M14	|76%|	72%|	9th grade|
|1|	Timofei Strowan|	M14	|83%|	NaN	|12th grade|
|2|	Silvain Poll|	M14	|83%|	NaN|	12th grade|
|3|	Lezley Pinxton|	M15	|80%|	86%|	11th grade|
|4|	Bernadene Saunper|	F17|	67%|	78%	|10th grade|

To this

||full_name|	gender_age|	grade|	exam|	score|
|---|---|---|---|---|---|
|0|	Moses Kirckman|	M14|	11th grade|	fractions|	69%|
|1|	Timofei Strowan|	M18|	11th grade|	fractions|	63%|
|2|	Silvain Poll|	M18|	9th grade|	fractions|	69%|
|3|	Lezley Pinxton|	M18|	11th grade|	fractions|	nan|
|4|	Bernadene Saunper|	F17	|11th grade|	fractions|	72%|

To reshape the data using pandas:

**Syntax:**

In [ ]:
df_name = pd.melt(
    frame = "df_name",
    id_vars = ["data_columns"...],
    value_vars = ["data_columns"...],
    value_name = "df_column",
    var_name = "df_column"
)

The parameters you provide are:

|arugment|description|
|---|---|
|frame| the DataFrame you want to melt|
|id_vars| the column(s) of the old DataFrame to preserve|
|value_vars| the column(s) of the old DataFrame that you want to turn into variables|
|value_name| what to call the column of the new DataFrame that stores the values|
|var_name| what to call the column of the new DataFrame that stores the variables|

Example:

To reshape the students dataset

In [9]:
students = pd.melt(
    frame = students,
    id_vars = ["full_name","gender_age","grade"],
    value_vars = ["fractions","probability"],
    value_name = "score",
    var_name = "exam"
)

In [10]:
students

           full_name gender_age       grade         exam score
0     Moses Kirckman        M14   9th grade    fractions   76%
1    Timofei Strowan        M14  12th grade    fractions   83%
2       Silvain Poll        M14  12th grade    fractions   83%
3     Lezley Pinxton        M15  11th grade    fractions   80%
4  Bernadene Saunper        F17  10th grade    fractions   67%
5     Moses Kirckman        M14   9th grade  probability   72%
6    Timofei Strowan        M14  12th grade  probability   NaN
7       Silvain Poll        M14  12th grade  probability   NaN
8     Lezley Pinxton        M15  11th grade  probability   86%
9  Bernadene Saunper        F17  10th grade  probability   78%

## Check for Duplicates

To check for duplicates, we can use the pandas function **.duplicated()**, which will return a Series telling us which rows are duplicate rows.

To check for duplicates in Python:

**Syntax:**

In [ ]:
#check for duplicate in a dataframe
df_name.duplicated()

#check for duplicate in a data column
df_name.column_name.duplicated()

Example:

In [11]:
students.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

The .duplicated() method returns a table of Boolean values to denote if duplicate existed.

To get the number of duplicate, we can simply sum up the boolean values.

In [12]:
students.duplicated().sum()

0

## Drop Duplicate

We can use the pandas .drop_duplicates() function to **remove all rows that are duplicates of another row.**

**Syntax:**

In [ ]:
df_name = df_name.drop_duplicates()

This will remove all rows any duplicated row

By specifying "subset" argument, this will **remove every row with a duplicate value in the specified column**

**Syntax:**

In [ ]:
df_name = df_name.drop_duplicates(subset=["df_name_column"...])

## Splitting by Index

In the students dataset, we see the "gender_age" data column contains 2 kind of information:

   * gender
   * age
   
We want to split this data into gender and age so that we can use these columns as separate features.

We can use the **pd.Series.str** to access the values of the series as strings and apply several methods to it.

To split by index

**Sytnax:**

In [ ]:
df_name["df_new_column_name"] = df_name["df_old_column_name"].str[index]

Example:

We want to split the "gender_age" data column in students dataset into 2 separate columns:
* gender
* age

In [13]:
students.gender_age

0    M14
1    M14
2    M14
3    M15
4    F17
5    M14
6    M14
7    M14
8    M15
9    F17
Name: gender_age, dtype: object

In [14]:
#gender is indicated by M/F
students["gender"] = students.gender_age.str[0]

In [15]:
#age is indicated by the number after gender
students["age"] = students.gender_age.str[1:]

In [16]:
#drop the gender_age data column
students.drop(
    columns=["gender_age"],
    inplace=True
)

In [17]:
students

           full_name       grade         exam score gender age
0     Moses Kirckman   9th grade    fractions   76%      M  14
1    Timofei Strowan  12th grade    fractions   83%      M  14
2       Silvain Poll  12th grade    fractions   83%      M  14
3     Lezley Pinxton  11th grade    fractions   80%      M  15
4  Bernadene Saunper  10th grade    fractions   67%      F  17
5     Moses Kirckman   9th grade  probability   72%      M  14
6    Timofei Strowan  12th grade  probability   NaN      M  14
7       Silvain Poll  12th grade  probability   NaN      M  14
8     Lezley Pinxton  11th grade  probability   86%      M  15
9  Bernadene Saunper  10th grade  probability   78%      F  17

## Split by Character

Similar to split by index, what if the string in the series is **join by some character** and we want to split by some character?

In the students dataset, we want to represent the "full_name" data column into 2 separate columns:
* first_name
* last_name

We can use the pd.Series.str to access the values of the series as strings and apply .split() method

**Syntax:**

In [ ]:
#define a Series to store the splited list in each row
var_name = df_name.column_name.str.split("character_code")

#use the .get() method to access the specific index
df_name["column_name"] = var_name.str.get(index)

Example:

To represent the "full_name" data column into 2 separate columns:
* first_name
* last_name

In [18]:
students

           full_name       grade         exam score gender age
0     Moses Kirckman   9th grade    fractions   76%      M  14
1    Timofei Strowan  12th grade    fractions   83%      M  14
2       Silvain Poll  12th grade    fractions   83%      M  14
3     Lezley Pinxton  11th grade    fractions   80%      M  15
4  Bernadene Saunper  10th grade    fractions   67%      F  17
5     Moses Kirckman   9th grade  probability   72%      M  14
6    Timofei Strowan  12th grade  probability   NaN      M  14
7       Silvain Poll  12th grade  probability   NaN      M  14
8     Lezley Pinxton  11th grade  probability   86%      M  15
9  Bernadene Saunper  10th grade  probability   78%      F  17

we need to split each entry of students.full_name by whitespace

In [19]:
#define a Series to store the splited list in each row
name_split = students.full_name.str.split(" ")

In [20]:
name_split

0       [Moses, Kirckman]
1      [Timofei, Strowan]
2         [Silvain, Poll]
3       [Lezley, Pinxton]
4    [Bernadene, Saunper]
5       [Moses, Kirckman]
6      [Timofei, Strowan]
7         [Silvain, Poll]
8       [Lezley, Pinxton]
9    [Bernadene, Saunper]
Name: full_name, dtype: object

In [21]:
#use the .get() method to access the specific index
students["first_name"] = name_split.str.get(0)
students["last_name"] = name_split.str.get(1)

In [22]:
students.drop(
    columns = ["full_name"],
    inplace=True
)

In [23]:
students

        grade         exam score gender age first_name last_name
0   9th grade    fractions   76%      M  14      Moses  Kirckman
1  12th grade    fractions   83%      M  14    Timofei   Strowan
2  12th grade    fractions   83%      M  14    Silvain      Poll
3  11th grade    fractions   80%      M  15     Lezley   Pinxton
4  10th grade    fractions   67%      F  17  Bernadene   Saunper
5   9th grade  probability   72%      M  14      Moses  Kirckman
6  12th grade  probability   NaN      M  14    Timofei   Strowan
7  12th grade  probability   NaN      M  14    Silvain      Poll
8  11th grade  probability   86%      M  15     Lezley   Pinxton
9  10th grade  probability   78%      F  17  Bernadene   Saunper

## Datatype of Column

Each column of a DataFrame can hold items of the same data type or dtype. 

The dtypes that pandas uses are: 
* float
* int
* bool
* datetime
* timedelta
* category
* object

Often, we want to convert between types so that we can do better analysis.

To access the datatype of each column in a dataset, we can use the attribute **.dtypes** in dataframe object

**Syntax:**

In [ ]:
df_name.dtypes

Example:

To access the datatype of all the column in students:

In [24]:
students.dtypes

grade         object
exam          object
score         object
gender        object
age           object
first_name    object
last_name     object
dtype: object

## String Parsing using Regex

Sometimes we need to modify strings in our DataFrames to help us transform them into more meaningful metrics.

In the students example, score is an object datatype, but we can't directly convert score from object type to numeric type **since score has a "$" character that prevent from converting**

we need to remove the "%" character from score

To remove character from each entry, we can use the .replace() method and use regex to represent the string character

**Syntax:**

In [ ]:
df_name["column_name"] = df_name.column_name.replace("[charactor_code]", "replace_by", regex=True)

replace() method:
* first agrument: represent the string you trying to replace in charactor code
* second agrument: represent the string that you trying to replace by
* third agrument: enable us to use regex

Example:

we need to remove the "%" character from score

In [25]:
students["score"] = students.score.replace("\%"," ", regex=True)

In [26]:
students

        grade         exam score gender age first_name last_name
0   9th grade    fractions   76       M  14      Moses  Kirckman
1  12th grade    fractions   83       M  14    Timofei   Strowan
2  12th grade    fractions   83       M  14    Silvain      Poll
3  11th grade    fractions   80       M  15     Lezley   Pinxton
4  10th grade    fractions   67       F  17  Bernadene   Saunper
5   9th grade  probability   72       M  14      Moses  Kirckman
6  12th grade  probability   NaN      M  14    Timofei   Strowan
7  12th grade  probability   NaN      M  14    Silvain      Poll
8  11th grade  probability   86       M  15     Lezley   Pinxton
9  10th grade  probability   78       F  17  Bernadene   Saunper

Now we can convert "score column" into numeric datatype

In [27]:
students["score"] = pd.to_numeric(students.score)

In [28]:
students.dtypes

grade          object
exam           object
score         float64
gender         object
age            object
first_name     object
last_name      object
dtype: object

Example:

We want to modify "grade" column so that there is only numeric component

In [29]:
#define a series with each entry splited by white space
grade_split = students.grade.str.split(" ")

In [30]:
grade_split

0     [9th, grade]
1    [12th, grade]
2    [12th, grade]
3    [11th, grade]
4    [10th, grade]
5     [9th, grade]
6    [12th, grade]
7    [12th, grade]
8    [11th, grade]
9    [10th, grade]
Name: grade, dtype: object

In [31]:
#set the "grade" column to the Oth index of grade_split
students["grade"] = grade_split.str.get(0)

In [32]:
students

  grade         exam  score gender age first_name last_name
0   9th    fractions   76.0      M  14      Moses  Kirckman
1  12th    fractions   83.0      M  14    Timofei   Strowan
2  12th    fractions   83.0      M  14    Silvain      Poll
3  11th    fractions   80.0      M  15     Lezley   Pinxton
4  10th    fractions   67.0      F  17  Bernadene   Saunper
5   9th  probability   72.0      M  14      Moses  Kirckman
6  12th  probability    NaN      M  14    Timofei   Strowan
7  12th  probability    NaN      M  14    Silvain      Poll
8  11th  probability   86.0      M  15     Lezley   Pinxton
9  10th  probability   78.0      F  17  Bernadene   Saunper

Now we need to remove the **"th"** in each entry of the "grade". We can do so by **replacing the non-numeric component with whitespace**

In [33]:
students["grade"] = students.grade.replace("[^\d]"," ",regex=True)

In [34]:
students

  grade         exam  score gender age first_name last_name
0   9      fractions   76.0      M  14      Moses  Kirckman
1  12      fractions   83.0      M  14    Timofei   Strowan
2  12      fractions   83.0      M  14    Silvain      Poll
3  11      fractions   80.0      M  15     Lezley   Pinxton
4  10      fractions   67.0      F  17  Bernadene   Saunper
5   9    probability   72.0      M  14      Moses  Kirckman
6  12    probability    NaN      M  14    Timofei   Strowan
7  12    probability    NaN      M  14    Silvain      Poll
8  11    probability   86.0      M  15     Lezley   Pinxton
9  10    probability   78.0      F  17  Bernadene   Saunper

Now we can convert "grade" column from object type to numeric type

In [35]:
students["grade"] = pd.to_numeric(students.grade)

In [36]:
students

   grade         exam  score gender age first_name last_name
0      9    fractions   76.0      M  14      Moses  Kirckman
1     12    fractions   83.0      M  14    Timofei   Strowan
2     12    fractions   83.0      M  14    Silvain      Poll
3     11    fractions   80.0      M  15     Lezley   Pinxton
4     10    fractions   67.0      F  17  Bernadene   Saunper
5      9  probability   72.0      M  14      Moses  Kirckman
6     12  probability    NaN      M  14    Timofei   Strowan
7     12  probability    NaN      M  14    Silvain      Poll
8     11  probability   86.0      M  15     Lezley   Pinxton
9     10  probability   78.0      F  17  Bernadene   Saunper

In [37]:
students.dtypes

grade           int64
exam           object
score         float64
gender         object
age            object
first_name     object
last_name      object
dtype: object

## Missing Value

We often have data with missing elements, as a result of a problem with the data collection process or errors in the way the data was stored. 

The missing elements normally show up as NaN (or Not a Number) values

To deal with missing value:
* drop all of the rows with a missing value
* fill the missing values with mean or some aggregated value

#### To drop all of the rows with missing value, we can use the **.dropna()** method.

**Syntax:**

In [ ]:
df_name = df_name.dropna()

If we want to remove every row with Nan value in the specific column, we can specify the "subset" argument

**Syntax:**

In [ ]:
df_name = df_name.dropna(subset=["column_name"...])

To check if there is any NaN value in the dataframe:

**Syntax:**

In [ ]:
#return a boolean table
df_name.isna()

#return number of NaN value 
df_name.isna().sum()

Example:

We want to drop the NaN value in all column in students dataset

In [39]:
students_no_nan = students.dropna()

In [40]:
#return a boolean table
students_no_nan.isna()

   grade   exam  score  gender    age  first_name  last_name
0  False  False  False   False  False       False      False
1  False  False  False   False  False       False      False
2  False  False  False   False  False       False      False
3  False  False  False   False  False       False      False
4  False  False  False   False  False       False      False
5  False  False  False   False  False       False      False
8  False  False  False   False  False       False      False
9  False  False  False   False  False       False      False

In [41]:
#return number of NaN value 
students_no_nan.isna().sum()

grade         0
exam          0
score         0
gender        0
age           0
first_name    0
last_name     0
dtype: int64

#### To fill all of the missing value with aggregated data, we can use the .fillna() method

**Syntax:**

In [ ]:
df_name = df_name.fillna(value={
    "column_name1":aggregated_data1,
    "column_name2":aggregated_data2,
    ...
})

Example:

In [42]:
students

   grade         exam  score gender age first_name last_name
0      9    fractions   76.0      M  14      Moses  Kirckman
1     12    fractions   83.0      M  14    Timofei   Strowan
2     12    fractions   83.0      M  14    Silvain      Poll
3     11    fractions   80.0      M  15     Lezley   Pinxton
4     10    fractions   67.0      F  17  Bernadene   Saunper
5      9  probability   72.0      M  14      Moses  Kirckman
6     12  probability    NaN      M  14    Timofei   Strowan
7     12  probability    NaN      M  14    Silvain      Poll
8     11  probability   86.0      M  15     Lezley   Pinxton
9     10  probability   78.0      F  17  Bernadene   Saunper

We want to fill in the NaN value in "score" column with the mean of the score

In [43]:
mean_score = students.score.mean()

students = students.fillna(value={
    "score":mean_score
})

In [44]:
students

   grade         exam   score gender age first_name last_name
0      9    fractions  76.000      M  14      Moses  Kirckman
1     12    fractions  83.000      M  14    Timofei   Strowan
2     12    fractions  83.000      M  14    Silvain      Poll
3     11    fractions  80.000      M  15     Lezley   Pinxton
4     10    fractions  67.000      F  17  Bernadene   Saunper
5      9  probability  72.000      M  14      Moses  Kirckman
6     12  probability  78.125      M  14    Timofei   Strowan
7     12  probability  78.125      M  14    Silvain      Poll
8     11  probability  86.000      M  15     Lezley   Pinxton
9     10  probability  78.000      F  17  Bernadene   Saunper